In [ ]:
#import pandas
import pandas as pd

# load dataset
df = pd.read_csv("Overall.csv", )

In [4]:
df.head()

,0,1,2,3,4,5,6,7,8
0,Date,Show,Average,IMDbRating,#Season,TotalSeason,Mean,Median,Quantile
1,2004-11-01,4,47.82608695652174,0.87,1,8,low,high,normal
2,2004-12-01,6,43.08695652173913,0.87,1,8,low,low,low
3,2005-01-01,6,45.73913043478261,0.87,1,8,low,low,normal
4,2005-02-01,7,49.65217391304348,0.87,1,8,high,high,normal